steps:
- name: 'node:22' 
  id: Install Dependencies
  entrypoint: npm
  dir: 'frontend'
  args: ['ci']

- name: 'node:22'
  id: Run Unit Tests
  entrypoint: npm
  dir: 'frontend'
  args: ['run', 'test:unit']
  waitFor: ['Install Dependencies']

- name: 'node:22'
  id: Run Build Script
  entrypoint: npm
  dir: 'frontend'
  env:
    - VITE_BUCKET_NAME=${_BUCKET_NAME}-stage
  args: ['run', 'build']
  waitFor: ['Run Unit Tests']

- name: 'gcr.io/cloud-builders/gsutil'
  id: Deploy to Staging
  dir: 'frontend'
  args: ['rsync', '-r', './dist', 'gs://${_BUCKET_NAME}-stage']
  waitFor: ['Run Build Script']

- name: 'gcr.io/cloud-builders/gsutil'
  id: Set HTML Headers
  dir: 'frontend'
  args: [
  '-m', # Execute operations in parallel
  'setmeta',
  '-h', 'Content-Type:text/html',
  '-h', 'Cache-Control:public, max-age=300, must-revalidate', # 5 minutes cache
  'gs://${_BUCKET_NAME}-stage/**.html'
  ]
  waitFor: ['Deploy to Staging']

- name: 'gcr.io/cloud-builders/gsutil'
  id: Set Assets Headers
  dir: 'frontend'
  args: [
  '-m',
  'setmeta',
  '-h', 'Cache-Control:public, max-age=31536000, immutable', # 1 year cache
  'gs://${_BUCKET_NAME}-stage/assets/*'
  ]
  waitFor: ['Set HTML Headers']

- name: mcr.microsoft.com/playwright:v1.55.0-noble
  entrypoint: bash
  dir: 'frontend'
  id: Run Playwright Tests
  env:
    - PLAYWRIGHT_BASE_URL=https://storage.googleapis.com
  args:
    - -c
    - |
      npm ci
      npx playwright install chromium
      npx playwright test
  waitFor: ['Set Assets Headers']

- name: 'gcr.io/cloud-builders/gsutil'
  id: Deploy to GCS
  dir: 'frontend'
  args: ['rsync', '-r', './dist', 'gs://${_BUCKET_NAME}-production']
  waitFor: ['Run Playwright Tests']

options:
  logging: CLOUD_LOGGING_ONLY
timeout: '600s'