steps:
- name: 'node:22' 
  id: Install Dependencies
  entrypoint: npm
  args: ['install']

- name: 'node:22'
  id: Run Build Script
  entrypoint: npm
  args: ['run', 'build']

- name: 'gcr.io/cloud-builders/gsutil'
  id: Deploy to GCS
  args: ['rsync', '-r', './dist', 'gs://task-manage']

timeout: '600s'