substitutions:
  _NOTIFICATION_EMAIL: 'peiyu20240219@gmail.com'
  _GMAIL_SENDER: 'peiyu20240219@gmail.com'

steps:
  # ==============================
  # STAGE 1: CONTINUOUS INTEGRATION (CI)
  # ==============================

  # Step 1: Install Dependencies
- name: 'node:22'
  entrypoint: 'npm'
  id: 'INSTALL_DEPS'
  dir: 'frontend'
  args: ['ci']

  # Step 2: Build Application
- name: 'node:22'
  entrypoint: 'npm'
  id: 'BUILD_APP'
  dir: 'frontend'
  env:
    - VITE_BUCKET_NAME=${_BUCKET_NAME}-stage
  args: ['run', 'build']
  waitFor: ['INSTALL_DEPS']

  # Step 3: Run Automated Tests
- name: 'node:22'
  entrypoint: 'npm'
  id: 'UNIT_TESTS'
  dir: 'frontend'
  args: ['run', 'test:unit']
  waitFor: ['INSTALL_DEPS']

  # ==============================
  # STAGE 2: CONTINUOUS DEPLOYMENT (CD)
  # ==============================

  # Step 4: Create Versioned Artifact
- name: 'gcr.io/cloud-builders/gsutil'
  id: 'DEPLOY_TO_STAGING'
  dir: 'frontend'
  args: ['rsync', '-r', './dist', 'gs://${_BUCKET_NAME}-stage']

  # Step 5: Run Staging Tests
- name: mcr.microsoft.com/playwright:v1.55.0-noble
  entrypoint: bash
  dir: 'frontend'
  id: 'E2E_TESTS'
  env:
    - PLAYWRIGHT_BASE_URL=https://storage.googleapis.com
    - VITE_BUCKET_NAME=${_BUCKET_NAME}-stage
  allowFailure: true
  args:
    - -c
    - |
      npm ci
      npx playwright install chromium
      npx playwright test --reporter=json,html
  waitFor: ['DEPLOY_TO_STAGING']

- name: mcr.microsoft.com/playwright:v1.55.0-noble
  entrypoint: bash
  dir: 'frontend'
  id: 'SEND_NOTIFICATION_EMAIL'
  allowFailure: true
  args:
    - '-c'
    - |
      if [ -f "test-results.json" ]; then
        # Check if any tests failed in the JSON results
        FAILED_COUNT=$(jq '[.suites[].specs[].tests[].results[] | select(.status=="failed")] | length' test-results.json)
        if [ "$$FAILED_COUNT" -eq 0 ]; then
          E2E_STATUS="PASSED"
          EMOJI="✅"
        else
          E2E_STATUS="FAILED"
          EMOJI="❌"
        fi
        
        # Get test statistics
        TOTAL_TESTS=$(jq '.suites[].specs[] | length' test-results.json | awk '{sum+=$1} END {print sum}')
        PASSED_TESTS=$(jq '[.suites[].specs[].tests[].results[] | select(.status=="passed")] | length' test-results.json)
      else
        E2E_STATUS="FAILED"
        EMOJI="❌"
        TOTAL_TESTS=0
        PASSED_TESTS=0
        FAILED_COUNT=0
      fi

      EMAIL_CONTENT=$(cat <<EOF
      From: ${_GMAIL_SENDER}
      To: ${_NOTIFICATION_EMAIL}
      Subject: $${EMOJI} E2E Tests $${E2E_STATUS} - ${REPO_NAME}
      MIME-Version: 1.0
      Content-Type: text/html; charset="UTF-8"

      <h2>$${EMOJI} E2E Test Results - ${REPO_NAME}</h2>
      <p><strong>Status:</strong> $${E2E_STATUS}</p>
      <p><strong>Project:</strong> ${PROJECT_ID}</p>
      <p><strong>Build ID:</strong> ${BUILD_ID}</p>
      <p><strong>Repository:</strong> ${REPO_NAME}</p>
      <p><strong>Branch:</strong> ${BRANCH_NAME}</p>
      <p><strong>Commit:</strong> ${COMMIT_SHA:0:8}</p>
      <p><a href='https://console.cloud.google.com/cloud-build/builds/${BUILD_ID}?project=${PROJECT_ID}'>View Build Logs</a></p>
      <p><a href='https://storage.googleapis.com/${_BUCKET_NAME}-stage/index.html'>View Staging Site</a></p>
      EOF)

      # Encode the email in base64 URL-safe format
      ENCODED_EMAIL=$(echo -n "$$EMAIL_CONTENT" | base64 -w 0 | tr '/+' '_-' | tr -d '=')

      # Send via Gmail API
      curl -X POST \
        "https://gmail.googleapis.com/gmail/v1/users/me/messages/send" \
        -H "Authorization: Bearer $${GMAIL_ACCESS_TOKEN}" \
        -H "Content-Type: application/json" \
        -d "{\"raw\": \"$$ENCODED_EMAIL\"}"
      
      echo "E2E test results notification sent!"
  waitFor: ['E2E_TESTS']
  secretEnv: ['GMAIL_ACCESS_TOKEN']

  # Step 8: Deploy to Production
- name: 'gcr.io/cloud-builders/gsutil'
  id: 'DEPLOY_TO_PRODUCTION'
  dir: 'frontend'
  args: ['rsync', '-r', './dist', 'gs://${_BUCKET_NAME}-production']
  waitFor: ['DEPLOY_TO_STAGING']

timeout: '600s'

options:
  logging: CLOUD_LOGGING_ONLY

availableSecrets:
  secretManager:
  - versionName: projects/174997059597/secrets/GMAIL_ACCESS_TOKEN/versions/latest
    env: 'GMAIL_ACCESS_TOKEN'
