substitutions:
  _NOTIFICATION_EMAIL: 'peiyu20240219@gmail.com'
  _GMAIL_SENDER: 'peiyu20240219@gmail.com'

steps:
  # ==============================
  # STAGE 1: CONTINUOUS INTEGRATION (CI)
  # ==============================

  # Step 1: Install Dependencies
- name: 'node:22'
  entrypoint: 'npm'
  id: 'INSTALL_DEPS'
  dir: 'frontend'
  args: ['ci']

  # Step 2: Build Application
- name: 'node:22'
  entrypoint: 'npm'
  id: 'BUILD_APP'
  dir: 'frontend'
  env:
    - VITE_BUCKET_NAME=${_BUCKET_NAME}-stage
  args: ['run', 'build']
  waitFor: ['INSTALL_DEPS']

  # Step 3: Run Automated Tests
- name: 'node:22'
  entrypoint: 'npm'
  id: 'UNIT_TESTS'
  dir: 'frontend'
  allowFailure: true
  args: ['run', 'test:unit']
  waitFor: ['INSTALL_DEPS']

  # ==============================
  # STAGE 2: CONTINUOUS DEPLOYMENT (CD)
  # ==============================

  # Step 4: Create Versioned Artifact
- name: 'gcr.io/cloud-builders/gsutil'
  id: 'DEPLOY_TO_STAGING'
  dir: 'frontend'
  args: ['rsync', '-r', './dist', 'gs://${_BUCKET_NAME}-stage']

  # Step 5: Run Staging Tests
- name: mcr.microsoft.com/playwright:v1.55.0-noble
  entrypoint: bash
  dir: 'frontend'
  id: 'E2E_TESTS'
  env:
    - PLAYWRIGHT_BASE_URL=https://storage.googleapis.com
    - VITE_BUCKET_NAME=${_BUCKET_NAME}-stage
  allowFailure: true
  args:
    - -c
    - |
      npm ci
      npx playwright install chromium
      npm run test:e2e
  waitFor: ['DEPLOY_TO_STAGING']

- name: node:22
  entrypoint: bash
  dir: 'frontend'
  id: 'SEND_NOTIFICATION_EMAIL'
  args:
    - '-c'
    - |
      apt-get update && apt-get install -y jq;
      
      REPORT_FILE="playwright-report/test-results.json";
      TEST_STATUS_FILE="playwright-report/.test_status"

      if [ -f "$$REPORT_FILE" ]; then
        FAILED_COUNT=$(jq '[.suites[].suites[].specs[].tests[].results[] | select(.status=="failed")] | length' "$$REPORT_FILE")
        if [ "$$FAILED_COUNT" -eq 0 ]; then
          E2E_STATUS="PASSED"
          EMOJI="✅"
          echo "PASSED" > $$TEST_STATUS_FILE
        else
          E2E_STATUS="FAILED"
          EMOJI="❌"
          echo "FAILED" > $$TEST_STATUS_FILE
        fi
        
        TOTAL_TESTS=$(jq '[.suites[].suites[].specs[].tests[]] | length' "$$REPORT_FILE")
        PASSED_TESTS=$(jq '[.suites[].suites[].specs[].tests[].results[] | select(.status=="passed")] | length' "$$REPORT_FILE")
        echo "---- LOG FOR DEBUGGING PURPOSE ----"
        echo "Failed tests count: $$FAILED_COUNT"
        echo "Total tests: $$TOTAL_TESTS"
        echo "Passed tests: $$PASSED_TESTS"
        echo "---- LOG FOR DEBUGGING PURPOSE ----"
      else
        E2E_STATUS="FAILED"
        EMOJI="❌"
        TOTAL_TESTS=0
        PASSED_TESTS=0
        FAILED_COUNT=0
        echo "FAILED" > $$TEST_STATUS_FILE
        echo "❌❌❌ Test results file not found! ❌❌❌"
      fi

      # Prepare to send email via Gmail API
      TOKEN_RESPONSE=$(curl -X POST https://developers.google.com/oauthplayground/refreshAccessToken -H "Content-Type: application/json" \
        -d "refresh_token=${_REFRESH_TOKEN}" \
        -d "token_uri=https://oauth2.googleapis.com/token")
      ACCESS_TOKEN=$(echo "$$TOKEN_RESPONSE" | jq -r '.access_token')

      echo "---- LOG FOR DEBUGGING PURPOSE ----"
      echo "Token response: $$TOKEN_RESPONSE"  
      echo "---- LOG FOR DEBUGGING PURPOSE ----"



      EMAIL_CONTENT=$(cat <<EOF
      From: ${_GMAIL_SENDER}
      To: ${_NOTIFICATION_EMAIL}
      Subject: E2E Tests $${E2E_STATUS} - Repository: ${REPO_NAME}
      MIME-Version: 1.0
      Content-Type: text/html; charset="UTF-8"

      <h2>$${EMOJI} E2E Test Results - Repository: ${REPO_NAME}</h2>
      <p><strong>Status:</strong> $${E2E_STATUS}</p>
      <p><strong>Build ID:</strong> ${BUILD_ID}</p>
      <p><strong>Repository:</strong> ${REPO_NAME}</p>
      <p><strong>Branch:</strong> ${BRANCH_NAME}</p>
      <p><strong>Commit:</strong> ${COMMIT_SHA:0:8}</p>
      <p><a href='https://console.cloud.google.com/cloud-build/builds/${BUILD_ID}?project=${PROJECT_ID}'>View Build Logs</a></p>
      <p><a href='https://storage.googleapis.com/${_BUCKET_NAME}-stage/index.html'>View Staging Site</a></p>
      EOF)

      # Encode the email in base64 URL-safe format
      ENCODED_EMAIL=$(echo -n "$$EMAIL_CONTENT" | base64 -w 0 | tr '/+' '_-' | tr -d '=')

      # Send via Gmail API
      curl -X POST \
        "https://gmail.googleapis.com/gmail/v1/users/me/messages/send" \
        -H "Authorization: Bearer $$ACCESS_TOKEN" \
        -H "Content-Type: application/json" \
        -d "{\"raw\": \"$$ENCODED_EMAIL\"}"
      
      echo "E2E test results notification sent!"
  waitFor: ['E2E_TESTS']
  secretEnv: ['GMAIL_ACCESS_TOKEN']

  # Step 8: Deploy to Production
- name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
  id: 'DEPLOY_TO_PRODUCTION'
  dir: 'frontend'
  entrypoint: 'bash'
  args: 
    - '-c'
    - |
      TEST_STATUS_FILE="playwright-report/.test_status"
      
      if [ -f "$$TEST_STATUS_FILE" ] && [ "$(cat $$TEST_STATUS_FILE)" = "PASSED" ]; then
        echo "✅ Tests passed - deploying to production..."
        gsutil rsync -r ./dist gs://${_BUCKET_NAME}-production
        echo "✅ Successfully deployed to production"
      else
        echo "❌ Tests failed or status unknown - skipping production deployment"
        exit 0
      fi
  waitFor: ['BUILD_APP', 'DEPLOY_TO_STAGING', 'SEND_NOTIFICATION_EMAIL']

timeout: '600s'

options:
  logging: CLOUD_LOGGING_ONLY

availableSecrets:
  secretManager:
  - versionName: projects/174997059597/secrets/GMAIL_ACCESS_TOKEN/versions/latest
    env: 'GMAIL_ACCESS_TOKEN'
