steps:
- name: 'node:22' 
  id: Install Dependencies
  entrypoint: npm
  dir: 'frontend'
  args: ['ci']

- name: 'node:22'
  id: Run Build Script
  entrypoint: npm
  dir: 'frontend'
  env:
    - VITE_BUCKET_NAME=/${_BUCKET_NAME}/
  args: ['run', 'build']

- name: mcr.microsoft.com/playwright:v1.55.0-noble
  entrypoint: bash
  dir: 'frontend'
  args:
    - -c
    - |
      npm ci
      npx playwright install chromium
      npm run test:e2e

- name: 'gcr.io/cloud-builders/gsutil'
  id: Deploy to GCS
  dir: 'frontend'
  args: ['rsync', '-r', './dist', 'gs://${_BUCKET_NAME}']

options:
  logging: CLOUD_LOGGING_ONLY
timeout: '600s'