options:
  logging: CLOUD_LOGGING_ONLY
  pubsubTopic: 'projects/grand-lamp-473611-d6/topics/cloud-builds'

steps:
  # ==============================
  # STAGE 1: CONTINUOUS INTEGRATION (CI)
  # ==============================

  # Step 1: Install Dependencies
- name: 'node:22'
  entrypoint: 'npm'
  id: 'INSTALL_DEPS'
  dir: 'frontend'
  args: ['ci']

  # Step 2: Build Application
- name: 'node:22'
  entrypoint: 'npm'
  id: 'BUILD_APP'
  dir: 'frontend'
  env:
    - VITE_BUCKET_NAME=${_BUCKET_NAME}-stage
  args: ['run', 'build']
  waitFor: ['INSTALL_DEPS']

  # Step 3: Run Automated Tests
- name: 'node:22'
  entrypoint: 'npm'
  id: 'UNIT_TESTS'
  dir: 'frontend'
  args: ['run', 'test:unit']
  waitFor: ['INSTALL_DEPS']

  # ==============================
  # STAGE 2: CONTINUOUS DEPLOYMENT (CD)
  # ==============================

  # Step 4: Create Versioned Artifact
- name: 'gcr.io/cloud-builders/gsutil'
  id: 'DEPLOY_TO_STAGING'
  dir: 'frontend'
  args: ['rsync', '-r', './dist', 'gs://${_BUCKET_NAME}-stage']

  # Step 5: Run Staging Tests
- name: mcr.microsoft.com/playwright:v1.55.0-noble
  entrypoint: bash
  dir: 'frontend'
  id: 'E2E_TESTS'
  env:
    - PLAYWRIGHT_BASE_URL=https://storage.googleapis.com
    - VITE_BUCKET_NAME=${_BUCKET_NAME}-stage
  args:
    - -c
    - |
      npm ci
      npx playwright install chromium
      npx playwright test
  waitFor: ['DEPLOY_TO_STAGING']

  # Step 8: Deploy to Production
- name: 'gcr.io/cloud-builders/gsutil'
  id: 'DEPLOY_TO_PRODUCTION'
  dir: 'frontend'
  args: ['rsync', '-r', './dist', 'gs://${_BUCKET_NAME}-production']
  waitFor: ['E2E_TESTS']

timeout: '600s'